### PR TITLE
Add a library of helper functions

### PR DESCRIPTION
**Pull request by PennyJim**
This is a draft pr as proof of how using these helper functions will look with context.

### CODE REVIEW

**Comment by TheFrenchTechMan** [comment]
whoops

**Comment by TheFrenchTechMan** [comment]
why the hell did I push on this fork

**Review by PennyJim — COMMENTED** [review]
> why the hell did I push on this fork 

Nah, that a side effect of me squashing the commits :)

**Comment by TheFrenchTechMan** [comment]
Is it a problem for you?

**Comment by PennyJim** [comment]
> Is it a problem for you?

Oh no.
Sorry for the late reply I got sucked into regex'ing

**Review by PennyJim — COMMENTED** [review]
I can't gurantee that I didn't fuck something up, but it starts up :D

And yes, fixing all the 'math' in the technology definitions tested my patience.

**Comment by TheFrenchTechMan** [comment]
@MrSmoothieHuman1 I'll let you look at this.

**Pull request merged**
